data = [
        ('channel', 'habr_com', 'программирование, технологии'),
        ('channel', 'moscowmap', 'новости'),
        ('channel', 'knigajivotnih1', 'природа, животные'),
        ('channel', 'miptru', 'вузы, наука'),
        ('channel', 'raiznews', 'CS go, киберспорт'),
        ('channel', 'bankrollo', 'экономика, финансы'),
        ('channel', 'myachPRO', 'футбол, спорт'),
        ('channel', 'fontankaspb', 'новости'),
        ('channel', 'realmadridcdf', 'футбол, спорт'),
        ('channel', 'bestiariy_mif', 'искусство, творчество'),
        ('channel', 'ihuntnoobs', 'киберспорт, CS'),
        ('channel', 'SwamCapital', 'экономика'),
        ('channel', 'truecatharsis', 'искусство, творчество'),
        ('channel', 'f1_sports', 'гонки, трансляции'),
        ('channel', 'deginc17', 'футбол, спорт'),
        ('bot', 'weather_bot', 'utility'),
        ('bot', 'finance_bot', 'finance'),
        ('mini_app', 'puzzle_app', 'games'),
        ('channel', 'tsiskaridzenews', 'искусство, творчество'),
        ('channel', 'moscowach', 'новости'),
        ('channel', 'yuriyshatunov_live', 'музыка, творчество'),
        ('channel', 'nikitanya713', 'химия, наука'),
        ('channel', 'etoznakmag', 'философия'),
        ('channel', 'nemnogoschastliveye', 'психология'),
        ('channel', 'ctrlvteam', 'футбол, спорт'),
        ('channel', 'ahmatova_anna1', 'литература'),
        ('channel', 'breakingmash', 'новости'),
        ('channel', 'bazabazon', 'новости'),
        ('channel', 'tolk_tolk', 'новости, история, социология'),
        ('channel', 'spydell_finance', 'рынки, экономика, аналитика'),
        ('channel', 'minaevlife', 'история, новости'),
        ('channel', 'etofaib', 'история, новости'),
        ('channel', 'pravilamagru', 'журнал, новости, исусство'),
        ('channel', 'russiansculture', 'история, культура'),
        ('channel', 'chtvmag', 'история, култура, новости'),
        ('channel', 'chinabackdoor', 'китай, культура, путешествия'),
        ('channel', 'china80s', 'китай, культура, путешествия'),
        ('channel', 'pognaliofficial', 'путешествия, культура'),
        ('channel', 'chinesespb', 'китай, интересные места'),
        ('channel', 'historyFAQ', 'история, факты'),
        ('channel', 'rusempfoto', 'история'),
        ('channel', 'latinpopacanski', 'история, искусство'),
        ('channel', 'getaroundrussia', 'путешествия, интересные места'),
        ('channel', 'trapeznick', 'еда'),
        ('channel', 'birzhevikstocksofficial2', 'финансы, экономика, инвестирование'),
        ('channel', 'art_polotno', 'фотографии, история, искусство'),
        ('channel', 'selfinvestor', 'финансы, экономика, инвестирование'),
        ('channel', 'cbrstocks', 'финансы, экономика, инвестирование'),
        ('channel', 'RBCCrypto', 'финансы, экономика, инвестирование'),
        ('channel', 'marathonecmagazine', 'спорт, бег'),
        ('channel', 'triathlon_rus', 'спорт, бег'),
        ('channel', 'ironstar_official', 'спорт, бег, триатлон'),
        ('channel', 'diehardrunning', 'спорт, бег, триатлон'),
        ('channel', 'runc_run', 'спорт, бег'),
        ('channel', 'russiarunninglife', 'спорт, бег'),
        ('channel', 'temalebedev', 'новости, сми, психология'),
        ('bot', 'PremuimSaverBot', 'видео'),
        ('channel', 'novosti_efir', 'новости, экономика, сми'),
        ('channel', 'headlines_for_traders', 'новости экономики, инвестирование, трейдинг'),
        ('channel', 'rusbri', 'политика, новости'),
        ('channel', 'costperlead', 'новости маркетинга, медиа'),
        ('channel', 'mknmoscow', 'история, интересные места'),
        ('channel', 'bitkogan_hotline', 'рынок, экономика'),
        ('channel', 'chinalanguageee', 'языки, культура'),
        ('channel', 'proved_is_here', 'новости, таможня'),
        ('channel', 'disruptors_official', 'технологии, бизнес, инновации'),
        ('channel', 'toporlive', 'новости без цензуры'),
        ('channel', 'topor', 'новости, сми'),
        ('channel', 'profenture', 'волонтерство, стажировки'),
        ('channel', 'phd4mipt_news', 'наука, физика'),
        ('channel', 'postupashki', 'вузы, поступление'),
        ('channel', 'postupashki_career', 'работа, собеседования'),
        ('channel', 'postypashki_old', 'работа, стажировки, IT'),
        ('channel', 'postupashki_physics', 'вузы, поступление'),
        ('channel', 'cpp_lects_rus', 'программирование, технологии'),
        ('channel', 'arkhlikbez', 'архитектура, искусство, дизайн'),
        ('channel', 'archnewschannel', 'дизайн, искусство'),
        ('channel', 'kosmo_off', 'космос, наука, звезды'),
        ('channel', 'kosmos149', 'космос, наука'),
        ('channel', 'canoesport', 'спорт, гребля'),
        ('channel', 'gorbilet_teatr', 'Питер, театры'),
        ('channel', 'teatr_msk', 'Москва, театры, события'),
        ('channel', 'MoscowAfish', 'афиша, театры'),
        ('channel', 'shantiheelsclass', 'обучение танцев'),
        ('channel', 'yandex_travel', 'советы, путешествия'),
        ('channel', 'travel_russia1', 'путешествия по России, места'),
]