data = [
            ('channel', 'habr_com', 'программирование, технологии'),
            ('channel', 'moscowmap', 'новости'),
            ('channel', 'knigajivotnih1', 'природа, животные'),
            ('channel', 'miptru', 'вузы'),
            ('channel', 'raiznews', 'CS go'),
            ('channel', 'bankrollo', 'экономика, финансы'),
            ('channel', 'myachPRO', 'футбол, спорт'),
            ('channel', 'fontankaspb', 'новости'),
            ('channel', 'realmadridcdf', 'футбол, спорт'),
            ('channel', 'bestiariy_mif', 'искусство, творчество'),
            ('channel', 'ihuntnoobs', 'киберспорт'),
            ('channel', 'SwamCapital', 'экономика'),
            ('channel', 'truecatharsis', 'искусство, творчество'),
            ('channel', 'f1_sports', 'гонки'),
            ('channel', 'deginc17', 'футбол, спорт'),
            ('bot', 'weather_bot', 'utility'),
            ('bot', 'finance_bot', 'finance'),
            ('mini_app', 'puzzle_app', 'games'),
            ('channel', 'tsiskaridzenews', 'искусство, творчество'),
            ('channel', 'moscowach', 'новости'),
            ('channel', 'yuriyshatunov_live', 'музыка, творчество'),
            ('channel', 'nikitanya713', 'химия, наука'),
            ('channel', 'etoznakmag', 'философия'),
            ('channel', 'nemnogoschastliveye', 'психология'),
            ('channel', 'ctrlvteam', 'футбол'),
            ('channel', 'ahmatova_anna1', 'литература'),
            ('channel', 'breakingmash', 'новости'),
            ('channel', 'bazabazon', 'новости'),
            ('channel', 'tolk_tolk', 'новости, история, социология'),
            ('channel', 'spydell_finance', 'рынки, экономика, аналитика'),
            ('channel', 'minaevlife', 'история, новости'),
            ('channel', 'etofaib', 'история, новости'),
            ('channel', 'pravilamagru', 'журнал, новости, исусство'),
            ('channel', 'russiansculture', 'история, культура'),
            ('channel', 'chtvmag', 'история, култура, новости'),
            ('channel', 'chinabackdoor', 'китай, культура, путешествия'),
            ('channel', 'china80s', 'китай, культура, путешествия'),
            ('channel', 'pognaliofficial', 'путешествия, культура'),
            ('channel', 'chinesespb', 'китай, интересные места'),
            ('channel', 'historyFAQ', 'история'),
            ('channel', 'rusempfoto', 'история'),
            ('channel', 'latinpopacanski', 'история, искусство'),
            ('channel', 'getaroundrussia', 'путешествия, интересные места'),
            ('channel', 'trapeznick', 'еда'),
            ('channel', 'birzhevikstocksofficial2', 'финансы, экономика, инвестирование'),
            ('channel', 'art_polotno', 'фотографии, история, искусство'),
            ('channel', 'selfinvestor', 'финансы, экономика, инвестирование'),
            ('channel', 'cbrstocks', 'финансы, экономика, инвестирование'),
            ('channel', 'RBCCrypto', 'финансы, экономика, инвестирование'),
            ('channel', 'marathonecmagazine', 'спорт, бег'),
            ('channel', 'triathlon_rus', 'спорт, бег'),
            ('channel', 'ironstar_official', 'спорт, бег, триатлон'),
            ('channel', 'diehardrunning', 'спорт, бег, триатлон'),
            ('channel', 'runc_run', 'спорт, бег'),
            ('channel', 'russiarunninglife', 'спорт, бег'),
]