data = [
#         ('channel', 'habr_com', 'программирование, технологии'),
#         ('channel', 'moscowmap', 'новости'),
#         ('channel', 'knigajivotnih1', 'природа, животные'),
#         ('channel', 'miptru', 'вузы, наука'),
#         ('channel', 'raiznews', 'CS go, киберспорт'),
#         ('channel', 'bankrollo', 'экономика, финансы'),
#         ('channel', 'myachPRO', 'футбол, спорт'),
#         ('channel', 'fontankaspb', 'новости'),
#         ('channel', 'realmadridcdf', 'футбол, спорт'),
#         ('channel', 'bestiariy_mif', 'искусство, творчество'),
#         ('channel', 'ihuntnoobs', 'киберспорт, CS'),
#         ('channel', 'SwamCapital', 'экономика'),
#         ('channel', 'truecatharsis', 'искусство, творчество'),
#         ('channel', 'f1_sports', 'гонки, трансляции'),
#         ('channel', 'deginc17', 'футбол, спорт'),
#         ('bot', 'weather_bot', 'utility'),
#         ('bot', 'finance_bot', 'finance'),
#         ('mini_app', 'puzzle_app', 'games'),
#         ('channel', 'tsiskaridzenews', 'искусство, творчество'),
#         ('channel', 'moscowach', 'новости'),
#         ('channel', 'yuriyshatunov_live', 'музыка, творчество'),
#         ('channel', 'nikitanya713', 'химия, наука'),
#         ('channel', 'etoznakmag', 'философия'),
#         ('channel', 'nemnogoschastliveye', 'психология'),
#         ('channel', 'ctrlvteam', 'футбол, спорт'),
#         ('channel', 'ahmatova_anna1', 'литература'),
#         ('channel', 'breakingmash', 'новости'),
#         ('channel', 'bazabazon', 'новости'),
#         ('channel', 'tolk_tolk', 'новости, история, социология'),
#         ('channel', 'spydell_finance', 'рынки, экономика, аналитика'),
#         ('channel', 'minaevlife', 'история, новости'),
#         ('channel', 'etofaib', 'история, новости'),
#         ('channel', 'pravilamagru', 'журнал, новости, исусство'),
#         ('channel', 'russiansculture', 'история, культура'),
#         ('channel', 'chtvmag', 'история, култура, новости'),
#         ('channel', 'chinabackdoor', 'китай, культура, путешествия'),
#         ('channel', 'china80s', 'китай, культура, путешествия'),
#         ('channel', 'pognaliofficial', 'путешествия, культура'),
#         ('channel', 'chinesespb', 'китай, интересные места'),
#         ('channel', 'historyFAQ', 'история, факты'),
#         ('channel', 'rusempfoto', 'история'),
#         ('channel', 'latinpopacanski', 'история, искусство'),
#         ('channel', 'getaroundrussia', 'путешествия, интересные места'),
#         ('channel', 'trapeznick', 'еда'),
#         ('channel', 'birzhevikstocksofficial2', 'финансы, экономика, инвестирование'),
#         ('channel', 'art_polotno', 'фотографии, история, искусство'),
#         ('channel', 'selfinvestor', 'финансы, экономика, инвестирование'),
#         ('channel', 'cbrstocks', 'финансы, экономика, инвестирование'),
#         ('channel', 'RBCCrypto', 'финансы, экономика, инвестирование'),
#         ('channel', 'marathonecmagazine', 'спорт, бег'),
#         ('channel', 'triathlon_rus', 'спорт, бег'),
#         ('channel', 'ironstar_official', 'спорт, бег, триатлон'),
#         ('channel', 'diehardrunning', 'спорт, бег, триатлон'),
#         ('channel', 'runc_run', 'спорт, бег'),
#         ('channel', 'russiarunninglife', 'спорт, бег'),
#         ('channel', 'temalebedev', 'новости, сми, психология'),
#         ('bot', 'PremuimSaverBot', 'видео'),
#         ('channel', 'novosti_efir', 'новости, экономика, сми'),
#         ('channel', 'headlines_for_traders', 'новости экономики, инвестирование, трейдинг'),
#         ('channel', 'rusbri', 'политика, новости'),
#         ('channel', 'costperlead', 'новости маркетинга, медиа'),
#         ('channel', 'mknmoscow', 'история, интересные места'),
#         ('channel', 'bitkogan_hotline', 'рынок, экономика'),
#         ('channel', 'chinalanguageee', 'языки, культура'),
#         ('channel', 'proved_is_here', 'новости, таможня'),
#         ('channel', 'disruptors_official', 'технологии, бизнес, инновации'),
#         ('channel', 'toporlive', 'новости без цензуры'),
#         ('channel', 'topor', 'новости, сми'),
#         ('channel', 'profenture', 'волонтерство, стажировки'),
#         ('channel', 'phd4mipt_news', 'наука, физика'),
#         ('channel', 'postupashki', 'вузы, поступление'),
#         ('channel', 'postupashki_career', 'работа, собеседования'),
#         ('channel', 'postypashki_old', 'работа, стажировки, IT'),
#         ('channel', 'postupashki_physics', 'вузы, поступление'),
#         ('channel', 'cpp_lects_rus', 'программирование, технологии'),
#         ('channel', 'arkhlikbez', 'архитектура, искусство, дизайн'),
#         ('channel', 'archnewschannel', 'дизайн, искусство'),
#         ('channel', 'kosmo_off', 'космос, наука, звезды'),
#         ('channel', 'kosmos149', 'космос, наука'),
#         ('channel', 'canoesport', 'спорт, гребля'),
#         ('channel', 'gorbilet_teatr', 'Питер, театры'),
#         ('channel', 'teatr_msk', 'Москва, театры, события'),
#         ('channel', 'MoscowAfish', 'афиша, театры'),
#         ('channel', 'shantiheelsclass', 'обучение танцев'),
#         ('channel', 'yandex_travel', 'советы, путешествия'),
#         ('channel', 'travel_russia1', 'путешествия по России, места'),
#         ('channel', 'game_talks', 'игры, видеоигры'),
#         ('channel', 'counter_strike2', 'CS2'),
#         ('channel', 'novaya_pishet', 'сми, новости'),
#         ('channel', 'ma4phys', 'физика'),
#         ('bot', 'fmusbot', 'музыка'),
#         ('channel', 'mayakovka', 'литература, библиотека'),
#         ('channel', 'itmo_uni', 'вузы, интститут, программирование'),
#         ('channel', 'mgimo_university', 'вузы, интститут, экономика'),
#         ('channel', 'spbuniversity1724', 'вузы, интститут'),
#         ('channel', 'mephi_of', 'вузы, интститут, физика'),
#         ('channel', 'rbc_news', 'новости, политика'),
#         ('channel', 'mozhno_potishe', 'книги, литература, цитаты'),
#         ('channel', 'RussianArchitecture', 'архитектура, дизайн'),
#         ('channel', 'ruskultur', 'места, культура'),
#         ('channel', 'durov_russia', 'Дуров, телеграм'),
#         ('channel', 'memachh', 'мемы, шутки, юмор'),
#         ('channel', 'givemetonru', 'криптовалюта'),

#     ('channel', 'okx_ru', 'криптовалюты'),
#     ('channel', 'leoday', 'юмор и развлечения'),
#     ('channel', 'moscowach', 'новости и СМИ'),
#     ('channel', 'novosti_efir', 'новости и СМИ'),
#     ('channel', 'hayzonn', 'криптовалюты'),
#     ('channel', 'toporlive', 'новости и СМИ'),
#     ('channel', 'memachh', 'юмор и развлечения'),
#     ('channel', 'Crypto_Woolf', 'криптовалюты'),
#     ('channel', 'rian_ru', 'новости и СМИ'),
#     ('channel', 'givemetonru', 'криптовалюты'),
#     ('channel', 'smi_rf_moskva', 'новости и СМИ'),
#     ('channel', 'tiktokupdatez', 'софт и приложения'),
#     ('channel', 'DeCenter', 'криптовалюты'),
#     ('channel', 'TikTokModCloud', 'софт и приложения'),
#     ('channel', 'tonlive', 'криптовалюты'),
#     ('channel', 'moscowmap', 'новости и СМИ'),
#     ('channel', 'investkingyru', 'криптовалюты'),
#     ('channel', 'temki_zvezdy', 'картинки и фото'),
#     ('channel', 'tonbase', 'криптовалюты'),
#     ('channel', 'GPTMainNews', 'технологии'),
#     ('channel', 'cultvcrypto', 'криптовалюты'),
#     ('channel', 'whackdoor', 'технологии'),
#     ('channel', 'mosguru', 'новости и СМИ'),
#     ('channel', 'eduardinvest', 'криптовалюты'),
#     ('channel', 'tonitsstyle', 'криптовалюты'),
#     ('channel', 'msk_live', 'новости и СМИ'),
#     ('channel', 'naebnet', 'технологии'),
#     ('channel', 'readovkanews', 'новости и СМИ'),
#     ('channel', 'technomotel', 'технологии'),
#     ('channel', 'RKadyrov_95', 'политика'),
#     ('channel', 'bbbreaking', 'новости и СМИ'),
#     ('channel', 'mskint', 'новости и СМИ'),
#     ('channel', 'hitvpn_news', 'технологии'),
#     ('channel', 'exploitex', 'технологии'),
#     ('channel', 'semenchuk', 'криптовалюты'),
#     ('channel', 'media1337', 'технологии'),
#     ('channel', 'milliardom', 'криптовалюты'),
#     ('channel', 'stikery_emodzi_memy', 'картинки и фото'),
#     ('channel', 'cybers', 'игры'),
#     ('channel', 'medvedev_telegram', 'политика'),
#     ('channel', 'maslennikovliga', 'блоги'),
#     ('channel', 'moscow', 'новости и СМИ'),
#     ('channel', 'litvintm', 'блоги'),
#     ('channel', 'tachki', 'транспорт'),
#     ('channel', 'TonAirDrop_ru', 'криптовалюты'),
#     ('channel', 'mosnews', 'новости и СМИ'),
#     ('channel', 'eeusd', 'криптовалюты'),
#     ('channel', 'RVvoenkor', 'политика'),
#     ('channel', 'bazabazon', 'новости и СМИ'),
#     ('channel', 'moscowachplus', 'новости и СМИ'),
#     ('channel', 'ostorozhno_novosti', 'новости и СМИ'),
#     ('channel', 'mir_supercell', 'игры'),
#     ('channel', 'fintopiochannel', 'криптовалюты'),
#     ('channel', 'adelimkhanov_95', 'политика'),
#     ('channel', 'tonmomentt', 'криптовалюты'),
#     ('channel', 'moscowportal', 'криптовалюты'),
#     ('channel', 'coinspacecrypto', 'криптовалюты'),
#     ('channel', 'podarokham', 'криптовалюты'),
#     ('channel', 'play_standoff2', 'игры'),
#     ('channel', 'game_doc', 'игры'),
#     ('channel', 'TgEmojis', 'telegram'),
#     ('channel', 'voina_belgorod_novosti', 'новости и СМИ'),

#     ('channel', 'ikniga', 'бизнес, книги, саморазвитие'),
#     ('channel', 'RUmerger', 'бизнес, финансы, инвестиции'),
#     ('channel', 'from_CEO', 'бизнес, управление, предпринимательство'),
#     ('channel', 'mosbusy', 'бизнес, московский бизнес, стартапы'),
#     ('channel', 'sellerx', 'бизнес, маркетплейсы, продажи'),
#     ('channel', 'Hour_25', 'бизнес, финансы, инвестиции'),
#     ('channel', 'Business_DNA_Russia', 'бизнес, российский бизнес, предпринимательство'),
#     ('channel', 'sberbusiness', 'бизнес, банковские услуги, финансы'),
#     ('channel', 'BusinessAlgorithm', 'бизнес, стратегии, предпринимательство'),
#     ('channel', 'commerc', 'бизнес, коммерция, предпринимательство'),
#     ('channel', 'kommerc', 'бизнес, е-коммерция, онлайн-продажи'),
#     ('channel', 'Financer_radar', 'бизнес, финансы, инвестиции'),
#     ('channel', 'bussideas', 'бизнес, идеи, предпринимательство'),
#     ('channel', 'DelovoyJur', 'бизнес, деловой журнал, предпринимательство'),
#     ('channel', 'retailrus', 'бизнес, ритейл, российский бизнес'),
#     ('channel', 'wbsellerofficial', 'бизнес, маркетплейсы, wildberries'),
#     ('channel', 'b_retail', 'бизнес, ритейл, предпринимательство'),
#     ('channel', 'gain_business', 'бизнес, предпринимательство, саморазвитие'),
#     ('channel', 'podkasty24', 'бизнес, подкасты, предпринимательство'),
#     ('channel', 'Bznsrussian', 'бизнес, российский бизнес, предпринимательство'),
#     ('channel', 'rybakovigor', 'бизнес, предпринимательство, лидерство'),
#     ('channel', 'Business_University', 'бизнес, образование, предпринимательство'),
#     ('channel', 'Busspod', 'бизнес, подкасты, предпринимательство'),
#     ('channel', 'yandexfintech', 'бизнес, финансы, технологии'),
#     ('channel', 'misli_bogatich', 'бизнес, мышление, предпринимательство'),
#     ('channel', 'dengivezde', 'бизнес, финансы, предпринимательство'),
#     ('channel', 'business_podcast', 'бизнес, подкасты, предпринимательство'),
#     ('channel', 'retail_bez', 'бизнес, ритейл, предпринимательство'),
#     ('channel', 'BusinesProjects', 'бизнес, проекты, предпринимательство'),
#     ('channel', 'BusinesAdvisor', 'бизнес, консультации, предпринимательство'),
#     ('channel', 'svoygectar', 'бизнес, сельское хозяйство, предпринимательство'),
#     ('channel', 'rus_buzines', 'бизнес, российский бизнес, стартапы'),
#     ('channel', 'tochkabis', 'бизнес, предпринимательство, стартапы'),
#     ('channel', 'Founder_Startup', 'бизнес, стартапы, предпринимательство'),
#     ('channel', 'master_businessa', 'бизнес, предпринимательство, саморазвитие'),
#     ('channel', 'Businesses_Upgrade', 'бизнес, развитие, предпринимательство'),
#     ('channel', 'financovich', 'бизнес, финансы, предпринимательство'),
#     ('channel', 'zakonycnexatg', 'бизнес, успех, предпринимательство'),
#     ('channel', 'KindBiz', 'бизнес, предпринимательство, этика бизнеса'),
#     ('channel', 'moscowachBusiness', 'бизнес, московский бизнес, предпринимательство'),
#     ('channel', 'BusinessAtmosphere', 'бизнес, предпринимательство, атмосфера бизнеса'),
#     ('channel', 'Finance_Instinct', 'бизнес, финансы, предпринимательство'),
#     ('channel', 'russian_ecom', 'бизнес, е-коммерция, предпринимательство'),
#     ('channel', 'sokolay', 'бизнес, предпринимательство, лидерство'),
#     ('channel', 'way_of_millionaire', 'бизнес, мотивация, предпринимательство'),
#     ('channel', 'namarketplacewithleo', 'бизнес, маркетплейсы, предпринимательство'),
#     ('channel', 'tutprobiz', 'бизнес, предпринимательство, стартапы'),
#     ('channel', 'ec_retail', 'бизнес, ритейл, медиа'),
#     ('channel', 'portnyaginlive', 'бизнес, предпринимательство, личный бренд'),
#     ('channel', 'avito_b2b', 'бизнес, b2b, предпринимательство'),
#     ('channel', 'mpgo_ru', 'бизнес, предпринимательство, стартапы'),
#     ('channel', 'temno', 'бизнес, предпринимательство, темная сторона бизнеса'),
#     ('channel', 'retail_kitchen', 'бизнес, ритейл, предпринимательство'),
#     ('channel', 'wbsharks', 'бизнес, маркетплейсы, предпринимательство'),
#     ('channel', 'business_motivators', 'бизнес, мотивация, предпринимательство'),
#     ('channel', 'mtokovinin', 'бизнес, предпринимательство, личный бренд'),
#     ('channel', 'Oskar_Hartmann', 'бизнес, предпринимательство, инвестиции'),
#     ('channel', 'startup_club24', 'бизнес, стартапы, предпринимательство'),

#     ('channel', 'maslennikovliga', 'блоги'),
#     ('channel', 'litvintm', 'блоги'),
#     ('channel', 'zubarefff', 'блоги'),
#     ('channel', 'bigpencil', 'блоги'),
#     ('channel', 'exilemusic13', 'блоги'),
#     ('channel', 'bloodysx', 'блоги'),
#     ('channel', 'borodylia0803', 'блоги'),
#     ('channel', 'nevzorovtv', 'блоги'),
#     ('channel', 'br1anm7ps', 'блоги'),
#     ('channel', 'evelone192gg', 'блоги'),
#     ('channel', 'elenaraytman', 'блоги'),
#     ('channel', 'bulkin_live', 'блоги'),
#     ('channel', 'Kuplinov_Telegram', 'блоги'),
#     ('channel', 'moscowtinderr', 'блоги'),
#     ('channel', 'paradeevich', 'блоги'),
#     ('channel', 'temalebedev', 'блоги'),
#     ('channel', 'geovaxue', 'блоги'),
#     ('channel', 'edisonfamilia', 'блоги'),
#     ('channel', 'yurydud', 'блоги'),
#     ('channel', 'ekaterina_mizulina', 'блоги'),
#     ('channel', 'GORDEYLIVE', 'блоги'),
#     ('channel', 'polunintrade', 'блоги'),
#     ('channel', 'alisherhateu', 'блоги'),
#     ('channel', 'egorikvtg', 'блоги'),
#     ('channel', 'sammyfam', 'блоги'),
#     ('channel', 'vladglenttg', 'блоги'),
#     ('channel', 'onastasiz', 'блоги'),
#     ('channel', 'koreshzy', 'блоги'),
#     ('channel', 'instasamkacore', 'блоги'),
#     ('channel', 'anyaischukkkk', 'блоги'),
#     ('channel', 'supestas1', 'блоги'),
#     ('channel', 'TheBadComedian', 'блоги'),
#     ('channel', 'A4omg', 'блоги'),
#     ('channel', 'DomerGrief', 'блоги'),
#     ('channel', 'zhidkovskiy_talk', 'блоги'),
#     ('channel', 'oieiei', 'блоги'),
#     ('channel', 'shadowkekw', 'блоги'),
#     ('channel', 'nebudetgg', 'блоги'),
#     ('channel', 'danila_gorilla', 'блоги'),
#     ('channel', 'imnotbozhena', 'блоги'),
#     ('channel', 'windy31room', 'блоги'),
#     ('channel', 'deepinstv', 'блоги'),
#     ('channel', 'dmlixxx', 'блоги'),
#     ('channel', 'marmok_yt', 'блоги'),
#     ('channel', 'mazellovvv', 'блоги'),
#     ('channel', 'batek_official', 'блоги'),
#     ('channel', 'DKNASASAL', 'блоги'),
#     ('channel', 'byzovahouse', 'блоги'),
#     ('channel', 'pinchulli', 'блоги'),
#     ('channel', 'plohoypacan', 'блоги'),
#     ('channel', 'luka_ebkov', 'блоги'),
#     ('channel', 'v_bonya', 'блоги'),
#     ('channel', 'slovopatsana', 'блоги'),
#     ('channel', 'camon_edward', 'блоги'),
#     ('channel', 'hardgabar', 'блоги'),
#     ('channel', 'milashkina_nekrasova', 'блоги'),
#     ('channel', 'petrovchanka_lera', 'блоги'),
#     ('channel', 'karnava1l', 'блоги'),
#     ('channel', 'strelets_molodec', 'блоги'),
#     ('channel', 'dikiidanik', 'блоги'),
#     ('channel', 'pel_video', 'блоги'),
#     ('channel', 'drakestudio', 'блоги'),
#     ('channel', 'marillokelhere', 'блоги'),
#     ('channel', 'dilalara753', 'блоги'),

#     ('channel', 'leoday', 'юмор, развлечения'),
#     ('channel', 'memachh', 'мемы, шутки, юмор'),
#     ('channel', 'why4ch', 'юмор, развлечения'),
#     ('channel', 'evo_memy', 'юмор, развлечения'),
#     ('channel', 'dvachannel', 'юмор, развлечения'),
#     ('channel', 'kruginapole', 'юмор, развлечения'),
#     ('channel', 'Cbpub', 'юмор, развлечения'),
#     ('channel', 'pezduza', 'юмор, развлечения'),
#     ('channel', 'telegrachan', 'юмор, развлечения'),
#     ('channel', 'mudak', 'юмор, развлечения'),
#     ('channel', 'pozor88', 'юмор, развлечения'),
#     ('channel', 'mossgirls', 'юмор, развлечения'),
#     ('channel', 'yaplakal', 'юмор, развлечения'),
#     ('channel', 'funXD_yumor_prikoly_memyXD', 'юмор, развлечения'),
#     ('channel', 'femalememes', 'юмор, развлечения'),
#     ('channel', 'pezduzalive', 'юмор, развлечения'),
#     ('channel', 'Lepragram', 'юмор, развлечения'),
#     ('channel', 'lifeyt', 'юмор, развлечения'),
#     ('channel', 'gusgagarik', 'юмор, развлечения'),
#     ('channel', 'zhiga', 'юмор, развлечения'),
#     ('channel', 'TNT_television', 'юмор, развлечения, ТНТ'),
#     ('channel', 'twitt_ota', 'юмор, развлечения, твиттер'),
#     ('channel', 'Mdk_pr', 'юмор, развлечения'),
#     ('channel', 'Jewish_hmr', 'юмор, развлечения, еврейский юмор'),
#     ('channel', 'xazayeva', 'юмор, развлечения'),
#     ('channel', 'nos_chanel', 'юмор, развлечения'),
#     ('channel', 'memsheroes', 'юмор, развлечения, диалоги'),
#     ('channel', 'pikabu', 'юмор, развлечения, пикабу'),
#     ('channel', 'theimprovisatorsshow', 'юмор, развлечения, импровизация'),
#     ('channel', 'video_dolboeba', 'юмор, развлечения, видео'),
#     ('channel', 'Yumor_humor', 'юмор, развлечения'),
#     ('channel', 'kikomedia', 'юмор, развлечения'),
#     ('channel', 'newradioru', 'юмор, развлечения, новое радио'),
#     ('channel', 'ptencoff', 'юмор, развлечения, видео'),
#     ('channel', 'savanichi', 'юмор, развлечения'),
#     ('channel', 'xaxaski_tg', 'юмор, развлечения'),
#     ('channel', 'rand2ch', 'юмор, развлечения, двач'),
#     ('channel', 'ru4chan', 'юмор, развлечения, 4chan'),
#     ('channel', 'joper5', 'юмор, развлечения, мысли'),
#     ('channel', 'formemas', 'юмор, развлечения, мемы, шаблоны'),
#     ('channel', 'retrogrademercury', 'юмор, развлечения'),
#     ('channel', 'tits_tweets', 'юмор, развлечения, твиттер'),
#     ('channel', 'anonimno_podslushano', 'юмор, развлечения, подслушано'),
#     ('channel', 'kruglyashiki', 'юмор, развлечения'),
#     ('channel', 'platinum_aneks', 'юмор, развлечения, анекдоты'),
#     ('channel', 'deadp47gaymer', 'юмор, развлечения'),
#     ('channel', 'znak_for_u', 'юмор, развлечения'),
#     ('channel', 'itmemes', 'юмор, развлечения, IT, программирование'),
#     ('channel', 'stories_foto_istorii', 'юмор, развлечения, сторис'),
#     ('channel', 'yu6_6kan', 'юмор, развлечения'),
#     ('channel', 'a_necdot69', 'юмор, развлечения, анекдоты, мемы'),
#     ('channel', 'jizajz', 'юмор, развлечения'),
#     ('channel', 'giff_dolboeba', 'юмор, развлечения, гифки'),
#     ('channel', 'testsapo', 'юмор, развлечения, тесты, квизы'),
#     ('channel', 'satyranos', 'юмор, развлечения, сатира'),
#     ('channel', 'antontelyakov', 'юмор, развлечения'),
#     ('channel', 'vinchkkk', 'юмор, развлечения, картинки, нейросеть'),
#     ('channel', 'molniya_vpn', 'юмор, развлечения, новости, VPN'),
#     ('channel', 'BEST7X7MEDIA', 'юмор, развлечения'),
#     ('channel', 'sms_future', 'юмор, развлечения, смс из будущего'),
#     ('channel', 'ynchq', 'юмор, развлечения'),
#     ('channel', 'azabraza84', 'юмор, развлечения, Азамат Мусагалиев'),
#     ('channel', 'membeztexta', 'юмор, развлечения, мемы, шаблоны'),
#     ('channel', 'community_memy', 'юмор, развлечения, мемы'),

#     ('channel', 'GPTMainNews', 'GPT, ChatGPT, Midjourney, технологии'),
#     ('channel', 'whackdoor', 'технологии'),
#     ('channel', 'naebnet', 'технологии'),
#     ('channel', 'technomotel', 'технологии'),
#     ('channel', 'hitvpn_news', 'технологии, VPN'),
#     ('channel', 'exploitex', 'технологии'),
#     ('channel', 'media1337', 'технологии'),
#     ('channel', 'chatgptv', 'IT, нейросети, технологии'),
#     ('channel', 'technomedia', 'технологии'),
#     ('channel', 'hiaimedia', 'технологии, AI'),
#     ('channel', 'techmedia', 'IT, технологии'),
#     ('channel', 'provod', 'технологии'),
#     ('channel', 'Wylsared', 'технологии'),
#     ('channel', 'milord_q', 'технологии'),
#     ('channel', 'bugfeature', 'технологии'),
#     ('channel', 'techno_media', 'технологии'),
#     ('channel', 'bugnotfeature', 'технологии'),
#     ('channel', 'concertzaal', 'технологии'),
#     ('channel', 'Romancev768', 'технологии'),
#     ('channel', 'remedia', 'технологии'),
#     ('channel', 'technolavka', 'технологии'),
#     ('channel', 'rozetked', 'технологии'),
#     ('channel', 'typespace', 'технологии'),
#     ('channel', 'biggeekru', 'технологии'),
#     ('channel', 'neuraldvig', 'нейросети, технологии'),
#     ('channel', 'yandex', 'технологии'),
#     ('channel', 'hack_less', 'технологии, безопасность'),
#     ('channel', 'd_code', 'технологии, программирование'),
#     ('channel', 'digital_neyroseti', 'IT, ChatGPT, технологии'),
#     ('channel', 'gpt_news', 'нейросети, технологии'),
#     ('channel', 'gptpublic', 'ChatGPT, нейросети'),
#     ('channel', 'TechGPTNews', 'технологии, GPT'),
#     ('channel', 'official_gigachat', 'GigaChat, технологии'),
#     ('channel', 'DeepTechNET', 'нейросети, технологии'),
#     ('channel', 'dvizhitall', 'технологии'),
#     ('channel', 'fon_tech', 'технологии'),
#     ('channel', 'ai_machinelearning_big_data', 'AI, машинное обучение'),
#     ('channel', 'YouFastVPN', 'безопасность, VPN'),
#     ('channel', 'backspace_mag', 'технологии'),
#     ('channel', 'mintsifry', 'технологии, государство'),
#     ('channel', 'kostylofficial', 'технологии'),
#     ('channel', 'techno_yandex', 'технологии, Яндекс'),
#     ('channel', 'rbtshki', 'технологии'),
#     ('channel', 'GPThelp_ru', 'ChatGPT, технологии'),
#     ('channel', 'neuralpony', 'нейросети'),
#     ('channel', 'codecamp', 'технологии, программирование'),
#     ('channel', 'mvideoandeldorado', 'технологии, электроника'),
#     ('channel', 'aiaiai', 'технологии, нейросети, боты'),
#     ('channel', 'feachermedia', 'технологии'),
#     ('channel', 'ai4telegram', 'AI, технологии'),
#     ('channel', 'mknewsru', 'технологии, компьютеры'),
#     ('channel', 'iPumpBrain', 'IT, тренды, технологии'),
#     ('channel', 'tehnicny', 'технологии'),
#     ('channel', 'discoveryit_channel', 'IT, технологии, бизнес'),
#     ('channel', 'spravportal_whocalls', 'безопасность, технологии'),
#     ('channel', 'lifegoodd1', 'технологии'),
#     ('channel', 'xor_journal', 'технологии'),
#     ('channel', 'robotsymphony', 'технологии, роботы'),
#     ('channel', 'devhub', 'технологии, разработка'),
#     ('channel', 'media_apple', 'Apple, технологии'),
#     ('channel', 'progbook', 'программирование, книги'),
#     ('channel', 'syntxfamily', 'технологии'),
#     ('channel', 'edya_robot', 'GPT, технологии'),

#     ('channel', 'etoznakmag', 'психология'),
#     ('channel', 'veronikastepanova20011', 'психология'),
#     ('channel', 'kristina_egiazarova14', 'психология'),
#     ('channel', 'sexology_vasilenko', 'психология'),
#     ('channel', 'tinderbye', 'психология'),
#     ('channel', 'Psychologs', 'психология'),
#     ('channel', 'psihzh', 'психология'),
#     ('channel', 'neirografica_formagiclife', 'психология'),
#     ('channel', 'Seda_Kasparova_news', 'психология'),
#     ('channel', 'labkovskiy', 'психология'),
#     ('channel', 'potok_samarina', 'психология'),
#     ('channel', 'satyadas_official', 'психология'),
#     ('channel', 'lpetranovskaya', 'психология'),
#     ('channel', 'deparpower', 'психология'),
#     ('channel', 'happy_intelligence', 'психология'),
#     ('channel', 'helga18plus', 'психология'),
#     ('channel', 'muzhitskaya', 'психология'),
#     ('channel', 'samorazvition', 'психология'),
#     ('channel', 'neuropsychology', 'психология'),
#     ('channel', 'transerfing_realnosti_tyt', 'психология'),
#     ('channel', 'milana_tarba', 'психология'),
#     ('channel', 'philosophicaI_thoughts', 'психология'),
#     ('channel', 'psyhoIogy', 'психология'),
#     ('channel', 'Adaconde1', 'психология'),
#     ('channel', 'psyxo1', 'психология'),
#     ('channel', 'Master_of_Habits', 'психология'),
#     ('channel', 'SilaSlov', 'психология'),
#     ('channel', 'accto_freud', 'психология'),
#     ('channel', 'silaslovv', 'психология'),
#     ('channel', 'larangsovetme', 'психология'),
#     ('channel', 'alinaguess', 'психология'),
#     ('channel', 'babazoyka', 'психология'),
#     ('channel', 'psy4love', 'психология'),
#     ('channel', 'motivation_psychoIogy', 'психология'),
#     ('channel', 'markbarton_mb', 'психология'),
#     ('channel', 'tvchernigovskya', 'психология'),
#     ('channel', 'bestijaia', 'психология'),
#     ('channel', 'yapsihologya', 'психология'),
#     ('channel', 'psihologiyaaaaaa0', 'психология'),
#     ('channel', 'perexodvtak', 'психология'),
#     ('channel', 'books_things', 'психология'),
#     ('channel', 'girlss_say', 'психология'),
#     ('channel', 'yasno_live', 'психология'),
#     ('channel', 'structure_happy', 'психология'),
#     ('channel', 'nesovetchik', 'психология'),
#     ('channel', 'vse_o_socionike', 'психология'),
#     ('channel', 'high_ver', 'психология'),
#     ('channel', 'drSit', 'психология'),
#     ('channel', 'etiketmaneri', 'психология'),
#     ('channel', 'motivationdushevn01', 'психология'),
#     ('channel', 'sheis10l10', 'психология'),
#     ('channel', 'belovainnapsy', 'психология'),
#     ('channel', 'olga_prokopova_s', 'психология'),
#     ('channel', 'womancan_mb', 'психология'),

#     ('channel', 'klientvsprav', 'Маркетинг, PR, реклама'),
#     ('channel', 'trendswhat', 'Маркетинг, PR, реклама'),
#     ('channel', 'trends', 'Маркетинг, PR, реклама'),
#     ('channel', 'trendsetter', 'Маркетинг, PR, реклама'),
#     ('channel', 'na_morozhenoe', 'Маркетинг, PR, реклама'),
#     ('channel', 'FamilyBots', 'Маркетинг, PR, реклама'),
#     ('channel', 'trendi', 'Маркетинг, PR, реклама'),
#     ('channel', 'ryanrun', 'Маркетинг, PR, реклама'),
#     ('channel', 'lovi_trand', 'Маркетинг, PR, реклаma'),
#     ('channel', 'trendach', 'Маркетинг, PR, реклама'),
#     ('channel', 'aaaredmarketing', 'Маркетинг, PR, реклама'),
#     ('channel', 'mediacom', 'Маркетинг, PR, реклама'),
#     ('channel', 'notypicmarketing', 'Маркетинг, PR, реклама'),
#     ('channel', 'malepeg', 'Маркетинг, PR, реклама'),
#     ('channel', 'not_marketing', 'Маркетинг, PR, реклама'),
#     ('channel', 'sosicka', 'Маркетинг, PR, реклама'),
#     ('channel', 'sale_caviar', 'Маркетинг, PR, реклама'),
#     ('channel', 'marketpsy', 'Маркетинг, PR, реклама'),
#     ('channel', 'brand_horse', 'Маркетинг, PR, реклама'),
#     ('channel', 'ca11_you', 'Маркетинг, PR, реклама'),
#     ('channel', 'oplata_skoro_budet', 'Маркетинг, PR, реклама'),
#     ('channel', 'retra', 'Маркетинг, PR, реклама'),
#     ('channel', 'pervmarketing', 'Маркетинг, PR, реклама'),
#     ('channel', 'lider', 'Маркетинг, PR, реклама'),
#     ('channel', 'prbezposhady', 'Маркетинг, PR, реклама'),
#     ('channel', 'boomers_TV', 'Маркетинг, PR, реклама'),
#     ('channel', 'creative', 'Маркетинг, PR, реклама'),
#     ('channel', 'kollegi', 'Маркетинг, PR, реклама'),
#     ('channel', 'drinkablewater', 'Маркетинг, PR, реклама'),
#     ('channel', 'MarketingQui', 'Маркетинг, PR, реклама'),
#     ('channel', 'trend_zavod', 'Маркетинг, PR, реклама'),
#     ('channel', 'collegi', 'Маркетинг, PR, реклама'),

#     ('channel', 'AETemp', 'дизайн'),
#     ('channel', 'DesignerGang', 'дизайн'),
#     ('channel', 'wtfont', 'дизайн'),
#     ('channel', 'sexyfont', 'дизайн'),
#     ('channel', 'photosed', 'дизайн'),
#     ('channel', 'figmadesign', 'дизайн'),
#     ('channel', 'FigmaDesign', 'дизайн'),
#     ('channel', 'stl_zone', 'дизайн'),
#     ('channel', 'BlenderDesign', 'дизайн'),
#     ('channel', 'designdealer', 'дизайн'),
#     ('channel', 'dsgn_tutorial', 'дизайн'),
#     ('channel', 'design_telega', 'дизайн'),
#     ('channel', 'JamMockup', 'дизайн'),
#     ('channel', 'Free3DSky', 'дизайн'),
#     ('channel', 'Gambody', 'дизайн'),
#     ('channel', 'morozprintm', 'дизайн'),
#     ('channel', 'free_brushes', 'дизайн'),
#     ('channel', 'pinterest_design_art', 'дизайн'),
#     ('channel', 'phhhphhh', 'дизайн'),
#     ('channel', 'designhunters', 'дизайн'),
#     ('channel', 'stl_for_Home', 'дизайн'),
#     ('channel', 'cgcours', 'дизайн'),
#     ('channel', 'Oasis3d', 'дизайн'),
#     ('channel', 'AEStorage', 'дизайн'),
#     ('channel', 'designer_ru', 'дизайн'),
#     ('channel', 'fontsch', 'дизайн'),
#     ('channel', 'photoshopforyou', 'дизайн'),
#     ('channel', 'mokaposhnaya', 'дизайн'),
#     ('channel', 'after_effects_motion', 'дизайн'),
#     ('channel', 'crucian31', 'дизайн'),
#     ('channel', 'dbooks', 'дизайн'),
#     ('channel', 'AdobeIllustratorDesign', 'дизайн'),
#     ('channel', 'pdigest', 'дизайн'),
#     ('channel', 'fontovik', 'дизайн'),
#     ('channel', 'SODesign', 'дизайн'),
#     ('channel', 'photoshop_hack', 'дизайн'),
#     ('channel', 'shrift_free', 'дизайн'),
#     ('channel', 'posterino', 'дизайн'),
#     ('channel', 'seif_designera', 'дизайн'),
#     ('channel', 'mockup_club', 'дизайн'),
#     ('channel', 'top_capcut', 'дизайн'),
#     ('channel', 'moCUPS', 'дизайн'),
#     ('channel', 'dsgn_box', 'дизайн'),
#     ('channel', 'ArchiveStl', 'дизайн'),
#     ('channel', 'designbirzha', 'дизайн'),
#     ('channel', 'figma2html', 'дизайн'),
#     ('channel', 'designrar', 'дизайн'),
#     ('channel', 'photoshop_guru', 'дизайн'),
#     ('channel', 'yudaevdesign', 'дизайн'),
#     ('channel', 'texture4photoshop', 'дизайн'),
#     ('channel', 'STL_Print', 'дизайн'),
#     ('channel', 'dsgn_teacher', 'дизайн'),
#     ('channel', 'brushprocreate', 'дизайн'),
#     ('channel', 'uxfromhell', 'дизайн'),
#     ('channel', 'you_are_designer', 'дизайн'),
#     ('channel', 'mockup_curator', 'дизайн'),
#     ('channel', 'figmaweb', 'дизайн'),
#     ('channel', 'a_study', 'дизайн'),
#     ('channel', 'Illustrationlessons', 'дизайн'),
#     ('channel', 'prvtdsgn', 'дизайн'),
#     ('channel', 'behancerdsgn', 'дизайн'),

#     ('channel', 'pokraslampas', 'искусство'),
#     ('channel', 'artgallery', 'искусство'),
#     ('channel', 'kartiny_arteriart', 'искусство'),
#     ('channel', 'i_am_artis', 'искусство'),
#     ('channel', 'kartiny_muzei_zhivopis', 'искусство'),
#     ('channel', 'oldradioteatr', 'искусство'),
#     ('channel', 'darkmgimo', 'искусство'),
#     ('channel', 'maneormone1', 'искусство'),
#     ('channel', 'msimonyan_literature', 'искусство'),
#     ('channel', 'kartiny_zhivopis_galereya', 'искусство'),
#     ('channel', 'kartiny2', 'искусство'),
#     ('channel', 'desastresguerra', 'искусство'),
    ('channel', 'ex_arte', 'искусство'),
    ('channel', 'sixtyfourmag', 'искусство'),
    ('channel', 'teatr_msk', 'искусство'),
    ('channel', 'leepotaa', 'искусство'),
    ('channel', 'aidolpolypoker', 'искусство'),
    ('channel', 'simpleartist', 'искусство'),
    ('channel', 'kartiny_tg', 'искусство'),
    ('channel', 'people_theatre', 'искусство'),
    ('channel', 'bestiariy_mif', 'искусство'),
    ('channel', 'futurione', 'искусство'),
    ('channel', 'teatrspb', 'искусство'),
    ('channel', 'muzei_tg', 'искусство'),
    ('channel', 'sv_bezrukov', 'искусство'),
    ('channel', 'kartiny_art_iskusstvo', 'искусство'),

    ('channel', 'matematik_andrei_channel', 'математика, образование'),
    ('channel', 'hacks_excel', 'excel, бухгалтерия, аналитика'),
    ('channel', 'reshatorgdz', 'гдз, образование'),
    ('channel', 'danirmath', 'математика, огэ, умскул'),
    ('channel', 'razgovory_o_vazhnom', 'разговоры о важном, образование'),
    ('channel', 'studyqa', 'стажировки, стипендии, обучение'),
    ('channel', 'nastya_umschool_russ', 'русский язык, огэ, умскул'),
    ('channel', 'physics_lib', 'физика, математика, программирование'),
    ('channel', 'depobr_mos', 'московское образование'),
    ('channel', 'Pedagogi_Rossii', 'педагоги, образование'),
    ('channel', 'konspekty_ege', 'биология, химия, образование'),
    ('channel', 'obr_mo', 'образование подмосковья'),
    ('channel', 'otvets1', 'ответы, образование'),
    ('channel', 'obshestvoznaika_el', 'обществознание, образование'),
    ('channel', 'justexcel24', 'excel, образование'),
    ('channel', 'razgovori_o_vajnom', 'разговоры о важном, образование'),
    ('channel', 'ravil_candi', 'обществознание, огэ, умскул'),
    ('channel', 'pedagogi_online', 'педагоги, инновации, образование'),
    ('channel', 'pepsi_exam', 'ответы, огэ, образование'),
    ('channel', 'sovuche', 'советские учебники, образование'),
    ('channel', 'otlichnica1', 'образование'),
    ('channel', 'ilchegg', 'математика, егэ, репетитор'),
    ('channel', 'kruzhok_ns', 'егэ, образование'),
    ('channel', 'hypeanswer', 'ответы, огэ, образование'),
    ('channel', 'stepbyshag', 'поступление, университет, образование'),
    ('channel', 'minprosrf', 'минпросвещения, образование'),
    ('channel', 'beyondsd', 'обучение за рубежом, образование'),
    ('channel', 'excelhackru', 'excel, образование'),
    ('channel', 'cptgrantov', 'образование'),
    ('channel', 'Shkoly_ru', 'школы, образование'),
    ('channel', 'umschool_official', 'умскул, образование'),
    ('channel', 'russichka_el', 'русский язык, егэ'),
    ('channel', 'matematichka_el', 'математика, егэ'),
    ('channel', 'google_sheets', 'google таблицы, образование'),
    ('channel', 't_uchebnik', 'учебник, образование'),
    ('channel', 'co_legko', 'семейное образование'),
    ('channel', 'Pedagogtyt', 'педагог, образование'),
    ('channel', 'minobrnaukiofficial', 'минобрнауки, образование'),
    ('channel', 'sbor25_me', 'сборники егэ, огэ, образование'),
    ('channel', 'otveti_oge77', 'ответы, огэ, образование'),
    ('channel', 'Teacher_club2022', 'учителя, образование'),
    ('channel', 'ege100_rus', 'русский язык, егэ'),
    ('channel', 'biofamily_ege', 'биология, егэ'),
    ('channel', 'anna_tochka_znaniy', 'образование'),
    ('channel', 'nudastudy', 'образование'),
    ('channel', 'osovtsovgovorit', 'образование'),
    ('channel', 'egoryakovleff', 'история, образование'),
    ('channel', 'excel_everyday', 'excel, образование')
]
