name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create CI test database
        run: |
          # Удаляем большую БД если она скачалась (будет битая)
          rm -f Backend/aggregator.db
          
          # Создаем легковесную тестовую БД
          python .github/create-test-db.py
          
          # Проверяем
          echo "📊 Database info:"
          ls -lh Backend/aggregator.db
          sqlite3 Backend/aggregator.db "SELECT COUNT(*) FROM projects;"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t your-app-name .

      - name: Test Docker container
        run: |
          # Запускаем контейнер
          docker run -d --name test-container -p 8000:8000 your-app-name
          sleep 15
          
          echo "📋 Container logs:"
          docker logs test-container
          
          # Проверяем здоровье
          if curl -s http://localhost:8000/health | grep -q "healthy"; then
            echo "✅ Health check passed"
          else
            echo "❌ Health check failed"
            docker logs test-container
            exit 1
          fi
          
          # Останавливаем контейнер
          docker stop test-container
          docker rm test-container