name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create CI test database
        run: |
          rm -f Backend/aggregator.db
          python .github/create-test-db.py
          echo "📊 Database created:"
          sqlite3 Backend/aggregator.db "SELECT COUNT(*) FROM projects;"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t your-app-name .

      - name: Test Docker container
        run: |
          # Запускаем контейнер
          docker run -d --name test-container -p 8000:8000 your-app-name
          
          # Ждем запуска
          sleep 10
          
          echo "📋 Container logs:"
          docker logs test-container
          
          # Проверяем health endpoint
          echo "🔍 Testing health endpoint..."
          response=$(curl -s -w "%{http_code}" http://localhost:8000/health)
          http_code=${response: -3}
          body=${response%???}
          
          echo "Response code: $http_code"
          echo "Response body: $body"
          
          if [ "$http_code" -eq 200 ] && echo "$body" | grep -q "healthy"; then
            echo "✅ Health check passed"
          else
            echo "❌ Health check failed"
            docker logs test-container
            exit 1
          fi
          
          # Дополнительная проверка root endpoint
          echo "🔍 Testing root endpoint..."
          if curl -s http://localhost:8000/ | grep -q "Telegram Bot"; then
            echo "✅ Root endpoint working"
          else
            echo "⚠️ Root endpoint check failed"
          fi
          
          # Останавливаем контейнер
          docker stop test-container
          docker rm test-container