name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t your-app-name .

      - name: Test Docker container
        run: |
          # Собираем образ
          docker build -t your-app-name .
          
          # Запускаем контейнер
          docker run -d --name test-container -p 8000:8000 your-app-name
          
          # Ждем запуска
          sleep 15
          
          # Проверяем, что контейнер запущен
          docker ps | grep test-container || (echo "❌ Container not running" && exit 1)
          
          # Проверяем логи на ошибки
          if docker logs test-container 2>&1 | grep -E "CRITICAL|ERROR|Error"; then
            echo "❌ Found errors in container logs:"
            docker logs test-container
            exit 1
          fi
          
          # Проверяем здоровье приложения
          if ! docker exec test-container curl -s -f http://localhost:8000/health > /dev/null; then
            echo "❌ Health check failed!"
            docker logs test-container
            exit 1
          fi
          
          echo "✅ All tests passed!"
          docker stop test-container
          docker rm test-container